{{- if .Values.letsencrypt.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ printf "%s-tls" .Values.ingress.hostname }}
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ printf "%s-tls" .Values.ingress.hostname }}
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end -}}