{{- if .Values.letsencrypt.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-tls" .Values.ingress.hostname }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ printf "%s-tls" .Values.ingress.hostname }}
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end -}}