{{- if .Values.webhook }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: webhook-ingress
  namespace: fleet-system
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: /deploy-webhook
          pathType: Prefix
          backend:
            service:
              name: gitjob
              port:
                number: 80
{{- end }}